[2024-08-02T21:14:52.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T21:14:52.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_dag.saving_top_post manual__2024-08-02T21:14:32.838194+00:00 [queued]>
[2024-08-02T21:14:52.298+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_dag.saving_top_post manual__2024-08-02T21:14:32.838194+00:00 [queued]>
[2024-08-02T21:14:52.299+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-02T21:14:52.328+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): saving_top_post> on 2024-08-02 21:14:32.838194+00:00
[2024-08-02T21:14:52.333+0000] {standard_task_runner.py:64} INFO - Started process 2247 to run task
[2024-08-02T21:14:52.335+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_dag', 'saving_top_post', 'manual__2024-08-02T21:14:32.838194+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpvi_yffnr']
[2024-08-02T21:14:52.336+0000] {standard_task_runner.py:91} INFO - Job 273: Subtask saving_top_post
[2024-08-02T21:14:52.392+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_dag.saving_top_post manual__2024-08-02T21:14:32.838194+00:00 [running]> on host 7df8ffa41b22
[2024-08-02T21:14:52.488+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_dag' AIRFLOW_CTX_TASK_ID='saving_top_post' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T21:14:32.838194+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T21:14:32.838194+00:00'
[2024-08-02T21:14:52.489+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T21:14:52.517+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T21:14:52.518+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/project_dag.py", line 145, in saveTopVoted
    f.write(f"{post['title']} {post['text']} {post['upvotes']}")
               ~~~~^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 721, in __getitem__
    self.__check_okay_to_chain()
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 500, in __check_okay_to_chain
    raise InvalidOperation("cannot set options after executing query")
pymongo.errors.InvalidOperation: cannot set options after executing query
[2024-08-02T21:14:52.530+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=reddit_dag, task_id=saving_top_post, run_id=manual__2024-08-02T21:14:32.838194+00:00, execution_date=20240802T211432, start_date=20240802T211452, end_date=20240802T211452
[2024-08-02T21:14:52.558+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 273 for task saving_top_post (cannot set options after executing query; 2247)
[2024-08-02T21:14:52.588+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-02T21:14:52.612+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T21:14:52.628+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
